# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Setup process.env
env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: gnBWeppVsLDoB1Cilos8Z94JeYZnwF8TCgaXjCh7OmJhIkUz1RAmvznUrL/u0tRpQAg2THLhdePJpH0VyLwb2CDo40+pybQwlac7mLmi+5fo5JZJq8ZyvOKAq0HVKaa2y/UyS6Mkm4Q/yZKnJY23k+XCSbRUn/+pMpNt2578qP6/U+4Ao9P2bxE2YOwAjj4oDcN0MtqzlQy/33p8GjwTNb4wkh9+oNg8BGUZab4rKC7De1G/c+7nc2GZDgw4LGPfVgoruxdDjc7o15ME9D/05+IMjY05bulAlh3WQcvCszZRqcYwu4J0Po/J28QCdxoLd38ieDlAYAA4LYnzys78xKTtjLM45U97v2K6p28TUBOTJtCuyLI4TjIfpaOphAyEGnaufW0tbXyF9BhibbNijpYpUtvL0RhwyDjC8TrV9vhUX8pESEwU/l4qPZ2EppgKGnc1mIlVzGnE5qZRY1kizPQuclPE7LxDGrj0irXNqWKoVGZz7jItoQl/Z48Tni9i+ocAJ1qGEJFyJKzLHJOJMUuWR88Q0eSDWidOd/nrrtGGcNwexUVJ4GIBkHW3uCqBuCa7rjgMTGoVHjIUuqtKTyAJI4sCbZsJCRehQOgFG8v/rEqUILosoLYRxRm0rshpdE+K96jBnIVmHXWJtsBF3EGgcBBC0Nn/QUtVHhEpuTw=
    # SAUCE_TOKENS
    - secure: jN/yZEy0NtlmkUAEn+fIXn6EpOkkqaq8Uar1xKDF5DqiNxKGxxdMSutZtgeKY7taDTMfuR+6S8sflbYQ8nYEhh6O+vNioBY6oYpFiJoCFi2RDNwaCB8a/pNzgpf0YQWoo8m9h6T2JdCOhU2GcZyhVpwua8To5TUUCRqEyhwfotgPDXFD3W+FRN2dZllXdTBBgXL242tbvmcUyQX2+yqyi+4pTQlzmxhm2mHiSka0yA6fVl8XxdwewhNgCdABiGVejJTutSI8TpT+evubMTLsDjJ58MIeXCAUA0KgVhMUax3t5RTQtLe/xkhFPFy8Vm5QDNr2WAp5azTB3eOrvM1zWLa/dZz8wRK8c4EQwYetFaaGyITrBupXy/f/xwXKKnHSFcJV9pLCXJpMZGeK0wL+5QtM0WL2D6gtp3O63Bh2U8E9FpImztcb3nuXtxatAJic/8ALPYm10KleT4let7WFZnOmHIyRp2lk/+cL0iaLWZ5MgGu5RCPucmLXYOroU9ZQnejHAW68o/VY7NpJKFr+DdnPuKZVUy9baRKvSuLZoGDhaXo21HlybJdMqdjKY07lgDSX6vP8W1nUlO1wkKCNmL8Mma/ZAK9zkcvhEbsz5zKgPdoNHRmlrT49sFUuN4ikPEmgvd9vZUacvWf6eCcTcJRRCvcyeQo1tP8WzQodJoo=
    - secure: eRNUkHgdTm5y3dh2bFUzQKysE2htZAOruWLsfRhlxepX7wmT44wTGVVAwhtMm//xo+U1qV10nfO2vio/fm92S9bWpUOZiMQBvfp2+2tex+oXvI1aXl+l7TN4iKGiPwfhTk8CtFm+H+tot0gUdlZcraOehR1Fcm58QWq43UTHLg3JC0dhdzjRO5KX4xHaoaViN+HCgSeqwgs4wObhgYyZya7x/9XJUUyeVWzO09PBBkPRTSkMmtX3/N0vHIAO/O0HzEXleOw5UVR58Zy0XCqUAgZFJXNuWWZxDhSrQ36SiairlmoeK7dvucisGHaCxGu7r//o49ckKrx4aE8sXPb3x3YTeVpoysxrzEWpeHUGifjyc/20ex5WoYLApDKGTgwJGjXtS3Hkga2ZWIxTIpP6iSfNYOQm3LvA/nUgbjGBRs2BtxrMxOHZVPyJFDIuK4MqsTsqwI+6Uj84V9y3BftgcEusNd0i5LBscd1cQJTcP+7Zp827qrapMUZCtCrAyYetkq/BQCkYZ3Wa43tNXIKypW4w8seyHqGUsUctvd46zrno1WN5xBAG0IEtjJ/8t0WgGGr3cEs8mtvcRwPLLR19jRTu2IrhLSPdI0yIai/rakLLKpYpkGvxlZ+7WmGY28UDyx8I+eWaLCinT1vDmx/W+b1NMxnRswOkenpb7t94jI8=

# Language options
language: node_js
node_js:
  - '0.12'
after_success:
  - 'export TRAVIS_PASSED=true'

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: wNYrTfWF7Hl64Kf5Ow1troWDoExCGKFqXkx0YYiINwzt45+SUJL37mF++9DYapLfrzgAeRUZ86McklxGmY9Id0mZorFppk6Brd+ZcWSrBLIlxduqqLCB8kSytBGfkUbYWy98MoDe8j1c4fZJNmV0kU0vsimZr0zv4t8+uEJB8WHB/KMA25BoPx0p+gp4fJM1gFOBaB7r1RTFnzTKnvJrCe8ADI4GIvB8DRsuXwdLgj502uwwQVRXBdFFbSsWrJUN+suiSACA9VXtJrgWHm9aqmc2sUCHlOLpsZPoFKaxgG/Lt2virfo0Paqwevrr26VMS6YCgO5lHZMoqzyn/N97vjr5ArywphkHoP/N2T2cjWGpQLLOxCVFqPqKdyF8WSfhr2PHmcPn1CFiB6uWVpJUAHea4FbYBOCyh2H8ddnXB2s22zGT35vYr7SEywcioR/WXS4R4YxRVUz6UglgOS7KAGyG/MxGoAXG6flhnlpmmvkRb3Fe6/Ybxe/91pzBlZVfHBMZg984jx3C5EbxGx+zus8kReumJgWr4t2MlaW0VCUYsw2PnqxCFN9MOJklnx4d6V/cFELTtWGkc3Oy7R8SmjXo2Niz7aL9mwa6Ges2y3C021UwrL9Ij6TEWNtkCsgU/+CM6WYHRosAPBbnBjX9fhWIck/HoUuGQLSOKZkreXQ=

# Cloud testing
after_deploy:
  - npm install
  - npm run test-cloud
